repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
-   repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
        args: [— maxkb=1000]
    -   id: check-ast
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/kplaube/pre-commit-dodgy
    rev: 0.0.2
    hooks:
     - id: dodgy
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.1
    hooks:
        - id: terraform_fmt
        - id: terraform_validate
        - id: terraform_tflint
        # - id: checkov
        - id: terraform_docs
        # - id: infracost_breakdown
