trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- template: templates/docker.yaml
  displayName: 'Build Docker container'
  inputs:
  - containerRegistry: eteckcontainerregistry.azurecr.io/eteck
