trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildandPushContainerImage
  steps:
  - template: templates/docker.yaml
    parameters:
      containerRegistry: "eteckContainerRegistryServiceConnectionDev2"
